Fix broken deployment pipeline (again) (#443)
Since #438, the Deployment workflow consistently fails with this error:

    Error: Unable to resolve @typescript/typescript-linux-x64. Either your platform is unsupported, or you are missing the package on disk.

TypeScript 7.0.2 declares its platform-specific binaries as optional dependencies, and we have `--omit optional` (since #157; not documented why).

Technically, only the Deployment workflow needs to be modified, but I'm making the same change to the Validation workflow for simplicity.

In the title, "(again)" refers to #414, which is completely unrelated but has the same title.

💡 `git show --color-words='--omit|.'`