Enable noImplicitOverride (TypeScript) (#439)
In #438, I intentionally disabled `noImplicitOverride` because it reported two of these type errors:

    error TS4114: This member must have an 'override' modifier because it overrides a member in the base class 'HTMLElement'.

This PR fixes them and enables `noImplicitOverride`.

💡 `git show --color-words='false|.'`