Migrate JavaScript wrapper to TypeScript (#438)
When [`elm-ts-types`] by @lydell appeared in my GitHub feed, I immediately realized that it should be able to prevent bugs similar to the one introduced in #268 and fixed in #269. This PR therefore converts the JavaScript wrapper to TypeScript, [using `elm-ts-types` and `elm-watch` to generate typings for the Elm ports][postprocess].

## About the diff

I wanted to minimize the differences between `index.js` and `index.ts` as much as possible, to make it obvious that the run-time meaning is unchanged. Only three classes of changes are made:

  * Type annotations are added to function parameters.
  * Some type assertions are added as necessary.
  * Subscription functions are made `async` as [recommended].

The added rule in `.gitignore` targets `src/typescript/zatacka.elm.d.ts`, which is generated by `elm-watch-postprocess.js` (e.g. as part of `npm run build`).

## TypeScript configuration

In `tsconfig.json`, I decided to sacrifice some explicitness in favor of brevity by not redundantly specifying options that (to my understanding) implicitly follow from `"strict": true`, namely the following (from the right-hand column [here]):

  * `alwaysStrict`
  * `strictNullChecks`
  * `strictBindCallApply`
  * `strictBuiltinIteratorReturn`
  * `strictFunctionTypes`
  * `strictPropertyInitialization`
  * `noImplicitAny`
  * `noImplicitThis`
  * `useUnknownInCatchVariables`

Out of those, the only ones explicitly specified are `strictNullChecks` and `strictPropertyInitialization`, which I needed to disable for the code to compile without extensive changes. The plan is to improve the configuration and code in future changesets.

Below follow explanations behind the options for which I didn't use the strictest possible value.

### `exactOptionalPropertyTypes`

Enabling it caused this error:

    error TS5052: Option 'exactOptionalPropertyTypes' cannot be specified without specifying option 'strictNullChecks'.

### `noImplicitOverride`

Enabling it caused two of these errors:

    error TS4114: This member must have an 'override' modifier because it overrides a member in the base class 'HTMLElement'.

### `strictNullChecks`

Enabling it caused a plethora of type errors that I don't want to deal with in this changeset.

### `strictPropertyInitialization`

Enabling it caused this error:

    error TS5052: Option 'strictPropertyInitialization' cannot be specified without specifying option 'strictNullChecks'.

As for `lib`, `module` and `target`, I just went with ES2020 for no particular reason.

[`elm-ts-types`]: https://github.com/lydell/elm-ts-types
[postprocess]: https://github.com/lydell/elm-ts-types/blob/v1.0.1/README.md?plain=1#L19
[here]: https://www.typescriptlang.org/tsconfig/#strict
[recommended]: https://github.com/lydell/elm-ts-types/tree/v1.0.1#why-return-promisevoid-when-subscribing-to-ports

💡 `git show --color-words=.`