Improve error handling in show-game-state script (#233)
In the context of `show-game-state.sh`, there are two known states that cause scanmem to fail:

  * The game isn't running. Then scanmem prints this on `stderr` after `> dump …`:

        error: failed to attach to 0, No such process
        error: read memory failed.

  * The game is starting. Then scanmem prints this on `stderr` after `> dump …`:

        error: read memory failed.

However, `show-game-state.sh` suppresses the error messages and only prints this:

    ⚠️  Empty input on stdin. Is the game running?

This PR gives us more fine-grained control over the error handling by collecting scanmem's `stderr` and checking it.

Piping scanmem's `stderr` to `interpret-scanmem-output.py` means that the latter receives this input:

    scanmem version 0.17
    libscanmem version 0.17

    Copyright (C) 2006-2017 Scanmem authors
    See https://github.com/scanmem/scanmem/blob/master/AUTHORS for a full author list

    scanmem comes with ABSOLUTELY NO WARRANTY; for details type `show warranty'.
    This is free software, and you are welcome to redistribute it
    under certain conditions; type `show copying' for details.

    info: maps file located at /proc/222078/maps opened.
    info: 61 suitable regions found.
    Please enter current value, or "help" for other commands.
    > option dump_with_ascii 0
    > dump 0x7fffc1c65ff6 72
    0x7fffc1c65ff6: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
    0x7fffc1c66006: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
    0x7fffc1c66016: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
    0x7fffc1c66026: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
    0x7fffc1c66036: 00 00 00 00 00 00 00 00
    > exit

So `parse_dump` is modified to only consider lines starting with `0x`.

💡 `git show --color-words='if .+|Empty input on stdin|\w+|.'`